services:
  - type: web  # Indica que este servicio es de tipo web
    name: mi-api-magneto
    runtime: docker  # Define el runtime para el servicio
    plan: free
    dockerfilePath: Dockerfile  # Ruta al Dockerfile
    envVars:  # Variables de entorno para tu aplicación
      - key: PORT  # Nombre de la variable de entorno
        value: 2003
    autoDeploy: true




